---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [--format, parsable]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.0
      hooks:
          - id: prettier
