---
name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches:
      - master

env:
  PROG: demake

jobs:
  stack-build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        stack: [2.9.1]
        ghc: [8.10.7]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: haskell/actions/setup@v1
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v3.0.9
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-ca-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}

      - uses: actions/cache@v3.0.9
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('**.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-work

      - name: Install dependencies
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --test-arguments=--format=progress

      - name: Prepare build artifact
        run: |
          rm -rf pkg && mkdir pkg/
          cp "$(stack exec -- which demake)" pkg/
          tar -cavf "demake-${{ matrix.os }}.tar" pkg/

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: demake-${{ matrix.os }}
          path: demake-${{ matrix.os }}.tar
          if-no-files-found: error
