---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build-release:
    name: Build release binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: demake
            asset_name: demake-linux-x86_64
          - os: macos-latest
            artifact_name: demake
            asset_name: demake-macos-x86_64_osx

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with:
          fast: ${{ github.ref != 'refs/heads/main' }}
      - name: Build
        run: |
          stack build --ghc-options -O2
          mkdir -p ${{ matrix.asset_name }}
          stack install --local-bin-path ${{ matrix.asset_name }}/
          tar -Jcvf ${{ matrix.asset_name }}.tar.xz ${{ matrix.asset_name }}/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.tar.xz
          asset_name: ${{ matrix.asset_name }}.tar.xz
          tag: ${{ github.ref }}
